// components/home/ProfileSidebar.tsx
import { Icon } from '@iconify/react'

import { config, linkBtns } from '@/config/site.config'

export default function HomeProfileSidebar() {
  return (
    <aside className="gh-vcard">
      <div className="vcard-header-mobile">
        <div className="vcard-avatar-wrap">
          <img
            src={config.avatarUrl}
            alt={`${config.name} 的头像照片`}
            className="vcard-avatar"
            width="260"
            height="260"
            decoding="async"
          />
          <div className="user-status-badge" title={config.status.message}>
            <span className="status-emoji">{config.status.emoji}</span>
          </div>
        </div>

        <div className="vcard-names">
          <h1 className="vcard-fullname">{config.name}</h1>
          <h2 className="vcard-username">cot.wiki</h2>
        </div>
      </div>

      <p className="vcard-bio">项目联系Cotovo@163.com</p>

      <ul className="vcard-details">
        <li>
          <Icon icon="ph:map-pin" className="d-icon" /> {config.infoTags.province}
        </li>
        <li>
          <Icon icon="ph:graduation-cap" className="d-icon" /> {config.infoTags.school}
        </li>
        <li>
          <Icon icon="ph:star" className="d-icon" /> {config.zodiac}
        </li>
        <li>
          <Icon icon="ph:calendar-blank" className="d-icon" /> {config.age}后
        </li>
      </ul>

      <div className="vcard-socials-wrapper">
        <div className="profile-divider" />
        <h3 className="social-title">社交链接</h3>
        <div className="social-list">
          {linkBtns.map((link, index) => (
            <a
              key={`${link.text}-${index}`}
              href={link.url}
              target="_blank"
              rel="noopener noreferrer me"
              className="gh-link social-link"
            >
              <Icon icon={link.icon} className="social-icon" style={{ color: link.color }} />
              <span>{link.text}</span>
            </a>
          ))}
        </div>
      </div>
    </aside>
  )
}

// components/home/ProfileSidebar.vue
<template>
  <aside class="gh-vcard">
    <div class="vcard-header-mobile">
      <div class="vcard-avatar-wrap">
        <img
          :src="config.avatarUrl"
          :alt="`${config.name} 的头像照片`"
          class="vcard-avatar"
          width="260"
          height="260"
          decoding="async"
        />
        <div class="user-status-badge" :title="config.status.message">
          <span class="status-emoji">{{ config.status.emoji }}</span>
        </div>
      </div>
  
      <div class="vcard-names">
        <h1 class="vcard-fullname">{{ config.name }}</h1>
        <h2 class="vcard-username">cot.wiki</h2>
      </div>
    </div>

    <p class="vcard-bio">项目联系Cotovo@163.com</p>

    <ul class="vcard-details">
      <li><Icon icon="ph:map-pin" class="d-icon" /> {{ config.infoTags.province }}</li>
      <li><Icon icon="ph:graduation-cap" class="d-icon" /> {{ config.infoTags.school }}</li>
      <li><Icon icon="ph:star" class="d-icon" /> {{ config.zodiac }}</li>
      <li><Icon icon="ph:calendar-blank" class="d-icon" /> {{ config.age }}后</li>
    </ul>

    <div class="vcard-socials-wrapper">
      <div class="profile-divider"></div>
      <h3 class="social-title">社交链接</h3>
      <div class="social-list">
        <a
          v-for="(link, index) in linkBtns"
          :key="index"
          :href="link.url"
          target="_blank"
          rel="noopener noreferrer me"
          class="gh-link social-link"
        >
          <Icon :icon="link.icon" class="social-icon" :style="{ color: link.color }" />
          <span>{{ link.text }}</span>
        </a>
      </div>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { config, linkBtns } from '~/config/site.config'
</script>

<style scoped>
.profile-divider {
  height: 1px;
  background: var(--gh-border-muted);
  margin: 16px 0;
}

.social-title {
  font-size: 16px;
  font-weight: 600;
  margin: 0 0 12px;
  color: var(--gh-fg);
}

.social-list {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.social-link {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
}

.social-icon {
  font-size: 18px;
}
@media (max-width: 768px) {
  .profile-divider {
    display: none;
  }
  .social-title {
    display: none;
  }
  .social-list {
    flex-direction: row;
    flex-wrap: wrap;
    gap: 10px;
  }
  .social-link span { display: none; }
  .social-icon { font-size: 20px; }
}
</style>
