// components/ArticleFeed.vue
<template>
  <section class="gh-card article-feed-card">
    <div class="card-header article-feed-header">
      <div class="article-feed-title-wrap">
        <Icon icon="ph:article-medium" class="card-h-icon" />
        <span class="card-h-title">文章</span>
      </div>

      <button
        class="article-refresh-btn"
        type="button"
        :disabled="pending || isRefreshing"
        aria-label="刷新文章列表"
        title="刷新文章列表"
        @click="refreshFeed"
      >
        <Icon icon="ph:arrows-clockwise" />
      </button>
    </div>

    <div class="card-body article-feed-body">
      <div class="article-feed-top">
        <p class="article-feed-intro">
          来自
          <a :href="feedData.sourceLink || blogHomeUrl" target="_blank" rel="noreferrer">
            {{ feedData.sourceTitle || '博客 RSS' }}
          </a>
          的最新文章
        </p>

        <p v-if="feedData.updatedAt" class="article-feed-updated">
          源更新时间：{{ formatFeedDate(feedData.updatedAt) }}
        </p>
      </div>

      <div v-if="pending" class="article-state">
        <Icon icon="ph:spinner-gap" class="spinner" />
        正在同步文章...
      </div>

      <div v-else-if="error" class="article-state error">
        <Icon icon="ph:warning-circle" />
        文章加载失败
      </div>

      <div v-else-if="articles.length" class="gh-issue-list">
        <a
          v-for="article in articles"
          :key="article.id"
          :href="article.url"
          target="_blank"
          rel="noreferrer"
          class="gh-issue-item"
        >
          <div class="issue-icon-wrap">
            <Icon icon="ph:record-fill" class="issue-icon" />
          </div>
          <div class="issue-content">
            <h3 class="issue-title">{{ article.title }}</h3>
            <div class="issue-meta">
              <span class="meta-id">#{{ article.id ? article.id.toString().slice(0, 5) : 'Feed' }}</span> opened on {{ formatFeedDate(article.publishedAt) }} by {{ feedData.sourceTitle }}
            </div>
          </div>
        </a>
      </div>

      <div v-else class="article-state">暂时还没有文章内容。</div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { Icon } from '@iconify/vue'
import { useRuntimeConfig } from '#imports'
import { formatDateZh } from '~/utils/format'

type ArticleFeedItem = {
  id: string
  title: string
  url: string
  summary: string
  publishedAt: string
}

type ArticleFeedResponse = {
  sourceTitle: string
  sourceLink: string
  updatedAt: string
  items: ArticleFeedItem[]
}

const runtimeConfig = useRuntimeConfig()
const blogHomeUrl = runtimeConfig.public.blogHomeUrl
const isRefreshing = ref(false)

const { data, pending, error, refresh } = await useFetch<ArticleFeedResponse>('/api/article-feed', {
  transform: payload => ({
    sourceTitle: payload?.sourceTitle || '',
    sourceLink: payload?.sourceLink || '',
    updatedAt: payload?.updatedAt || '',
    items: payload?.items ?? []
  }),
  default: () => ({
    sourceTitle: '',
    sourceLink: '',
    updatedAt: '',
    items: [] as ArticleFeedItem[]
  })
})

const feedData = computed<ArticleFeedResponse>(() => {
  return data.value as ArticleFeedResponse
})

const articles = computed(() => feedData.value.items ?? [])

function formatFeedDate(value: string) {
  return formatDateZh(value)
}

async function refreshFeed() {
  if (pending.value || isRefreshing.value) {
    return
  }

  isRefreshing.value = true

  try {
    await refresh()
  } finally {
    isRefreshing.value = false
  }
}
</script>

<style scoped>
.article-feed-header {
  justify-content: space-between;
}

.article-feed-title-wrap {
  display: flex;
  align-items: center;
  gap: 8px;
}

.article-refresh-btn {
  background: transparent;
  border: none;
  border-radius: 4px;
  color: var(--gh-fg-muted);
  font-size: 16px;
  cursor: pointer;
  padding: 4px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: color 0.2s, background-color 0.2s;
}

.article-refresh-btn:hover {
  color: var(--gh-fg);
  background-color: var(--gh-bg-subtle);
}

.article-refresh-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.article-feed-body {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.article-feed-top {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  gap: 10px;
}

.article-feed-intro,
.article-feed-updated {
  margin: 0;
  color: var(--gh-fg-muted);
  font-size: 13px;
}

.article-feed-intro a {
  color: var(--gh-accent);
  text-decoration: none;
}

.article-feed-intro a:hover {
  text-decoration: underline;
}

.article-state {
  min-height: 180px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  color: var(--gh-fg-muted);
  font-size: 14px;
}

.article-state.error {
  color: #cf222e;
}

.spinner {
  animation: spin 1s linear infinite;
  font-size: 18px;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.gh-issue-list {
  display: flex;
  flex-direction: column;
  border: 1px solid var(--gh-border);
  border-radius: 6px;
  overflow: hidden;
}

.gh-issue-item {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  padding: 12px 16px;
  text-decoration: none;
  border-bottom: 1px solid var(--gh-border-muted);
  background: var(--gh-bg);
  transition: background-color 0.15s;
}

.gh-issue-item:last-child {
  border-bottom: none;
}

.gh-issue-item:hover {
  background-color: var(--gh-bg-subtle);
}

.issue-icon-wrap {
  flex-shrink: 0;
  margin-top: 2px;
}

.issue-icon {
  color: var(--gh-success);
  font-size: 16px;
}

.issue-content {
  display: flex;
  flex-direction: column;
  gap: 2px;
  min-width: 0;
}

.issue-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: var(--gh-fg);
  line-height: 1.3;
}

.issue-title:hover {
  color: var(--gh-accent);
}

.issue-meta {
  font-size: 12px;
  color: var(--gh-fg-muted);
  line-height: 1.4;
}

@media (max-width: 768px) {
  .article-feed-body {
    gap: 12px;
  }

  .gh-issue-item {
    padding: 12px;
  }
}
</style>

// components/ArticleFeed.tsx
'use client'

import { Icon } from '@iconify/react'
import { useEffect, useState } from 'react'

import type { ArticleFeedResponse } from '@/lib/article-feed'
import { publicSiteConfig } from '@/lib/site'
import { formatDateZh } from '@/utils/format'

type ArticleFeedProps = {
  initialData: ArticleFeedResponse
}

export default function ArticleFeed({ initialData }: ArticleFeedProps) {
  const [feedData, setFeedData] = useState<ArticleFeedResponse>(initialData)
  const [pending, setPending] = useState(false)
  const [error, setError] = useState(false)
  const [isRefreshing, setIsRefreshing] = useState(false)

  useEffect(() => {
    if (initialData.items.length) {
      return
    }

    let cancelled = false

    const load = async () => {
      setPending(true)
      setError(false)

      try {
        const payload = await fetchArticleFeed()
        if (!cancelled) {
          setFeedData(payload)
        }
      } catch {
        if (!cancelled) {
          setError(true)
        }
      } finally {
        if (!cancelled) {
          setPending(false)
        }
      }
    }

    void load()

    return () => {
      cancelled = true
    }
  }, [initialData.items.length])

  const articles = feedData.items ?? []

  async function refreshFeed() {
    if (pending || isRefreshing) {
      return
    }

    setIsRefreshing(true)
    setError(false)

    try {
      const payload = await fetchArticleFeed()
      setFeedData(payload)
    } catch {
      setError(true)
    } finally {
      setIsRefreshing(false)
    }
  }

  return (
    <section className="gh-card article-feed-card">
      <div className="card-header article-feed-header">
        <div className="article-feed-title-wrap">
          <Icon icon="ph:article-medium" className="card-h-icon" />
          <span className="card-h-title">文章</span>
        </div>

        <button
          className="article-refresh-btn"
          type="button"
          disabled={pending || isRefreshing}
          aria-label="刷新文章列表"
          title="刷新文章列表"
          onClick={refreshFeed}
        >
          <Icon icon="ph:arrows-clockwise" />
        </button>
      </div>

      <div className="card-body article-feed-body">
        <div className="article-feed-top">
          <p className="article-feed-intro">
            来自{' '}
            <a href={feedData.sourceLink || publicSiteConfig.blogHomeUrl} target="_blank" rel="noreferrer">
              {feedData.sourceTitle || '博客 RSS'}
            </a>{' '}
            的最新文章
          </p>

          {feedData.updatedAt ? (
            <p className="article-feed-updated">源更新时间：{formatDateZh(feedData.updatedAt)}</p>
          ) : null}
        </div>

        {pending ? (
          <div className="article-state">
            <Icon icon="ph:spinner-gap" className="spinner" />
            正在同步文章...
          </div>
        ) : error ? (
          <div className="article-state error">
            <Icon icon="ph:warning-circle" />
            文章加载失败
          </div>
        ) : articles.length ? (
          <div className="gh-issue-list">
            {articles.map(article => (
              <a
                key={article.id}
                href={article.url}
                target="_blank"
                rel="noreferrer"
                className="gh-issue-item"
              >
                <div className="issue-icon-wrap">
                  <Icon icon="ph:record-fill" className="issue-icon" />
                </div>
                <div className="issue-content">
                  <h3 className="issue-title">{article.title}</h3>
                  <div className="issue-meta">
                    <span className="meta-id">#{article.id ? article.id.toString().slice(0, 5) : 'Feed'}</span>{' '}
                    opened on {formatDateZh(article.publishedAt)} by {feedData.sourceTitle}
                  </div>
                </div>
              </a>
            ))}
          </div>
        ) : (
          <div className="article-state">暂时还没有文章内容。</div>
        )}
      </div>
    </section>
  )
}

async function fetchArticleFeed() {
  const response = await fetch('/api/article-feed', { cache: 'no-store' })

  if (!response.ok) {
    throw new Error('Article feed request failed')
  }

  const payload = (await response.json()) as Partial<ArticleFeedResponse>

  return {
    sourceTitle: payload.sourceTitle || '',
    sourceLink: payload.sourceLink || '',
    updatedAt: payload.updatedAt || '',
    items: payload.items ?? []
  } satisfies ArticleFeedResponse
}
